package com.grain.entity.user;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.grain.entity.Area;

/**
 * TFarmeruser generated by hbm2java
 * 储粮农户用户
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_farmeruser")
public class FarmerUser implements java.io.Serializable {

	private String username;
	private Area area;
	private String smFarmer;
	private String realname;
	private String moblie;
	private String address;
	private Double longitude;
	private Double latitude;
	private Double altitude;
	private String postcode;
	String password;
	private String modifer;
	private Date modifydate;
	
	/** 角色 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="roleid", nullable = true)
	//@JsonUnwrapped
	@JsonIgnoreProperties(value={"hibernateLazyInitializer","handler",
			"isSystem",	"resourceIds","description","createDate","modifyDate"})
	private Role role; 


	@Id
	@Column(name = "username", unique = true, nullable = false, length = 10)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "direct")
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@Column(name = "sm_farmer", nullable = false, length = 30)
	public String getSmFarmer() {
		return this.smFarmer;
	}

	public void setSmFarmer(String smFarmer) {
		this.smFarmer = smFarmer;
	}

	@Column(name = "realname", nullable = false, length = 30)
	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	@Column(name = "moblie", length = 20)
	public String getMoblie() {
		return this.moblie;
	}

	public void setMoblie(String moblie) {
		this.moblie = moblie;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "longitude", precision = 22, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude", precision = 22, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "altitude", precision = 22, scale = 0)
	public Double getAltitude() {
		return this.altitude;
	}

	public void setAltitude(Double altitude) {
		this.altitude = altitude;
	}

	@Column(name = "postcode", length = 10)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "modifer", length = 30)
	public String getModifer() {
		return this.modifer;
	}

	public void setModifer(String modifer) {
		this.modifer = modifer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifydate", length = 19)
	public Date getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}
	@Column(name = "password", length = 255)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
