package com.grain.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TFarmer generated by hbm2java
 * 农户信息表
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_farmer")
@JsonIgnoreProperties(value={"hibernateLazyInitializer","handler",
		"insectsCollectionOnFarmers"
		})
public class Farmer implements java.io.Serializable {

	private String smFarmer;
	private Area area;
	private String nameFamer;
	private String address;
	private Double longitude;
	private Double latitude;
	private Double altitude;
	private String postcode;
	private String phone;
	private Integer population;
	private String economic;
	private String traffic;
	private String geography;
	private String modifer;
	private String modifydate;
	private Set<TInsectsCollectionOnFarmer> insectsCollectionOnFarmers = new HashSet<TInsectsCollectionOnFarmer>(0);


	@Id
	@Column(name = "sm_farmer", unique = true, nullable = false, length = 30)
	public String getSmFarmer() {
		return this.smFarmer;
	}

	public void setSmFarmer(String smFarmer) {
		this.smFarmer = smFarmer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "direct")
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@Column(name = "name_famer", nullable = false, length = 30)
	public String getNameFamer() {
		return this.nameFamer;
	}

	public void setNameFamer(String nameFamer) {
		this.nameFamer = nameFamer;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "longitude", precision = 22, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude", precision = 22, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "altitude", precision = 22, scale = 0)
	public Double getAltitude() {
		return this.altitude;
	}

	public void setAltitude(Double altitude) {
		this.altitude = altitude;
	}

	@Column(name = "postcode", length = 10)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "phone", nullable = false, length = 60)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "population")
	public Integer getPopulation() {
		return this.population;
	}

	public void setPopulation(Integer population) {
		this.population = population;
	}

	@Column(name = "Economic", length = 60)
	public String getEconomic() {
		return this.economic;
	}

	public void setEconomic(String economic) {
		this.economic = economic;
	}

	@Column(name = "traffic", length = 60)
	public String getTraffic() {
		return this.traffic;
	}

	public void setTraffic(String traffic) {
		this.traffic = traffic;
	}

	@Column(name = "geography", length = 60)
	public String getGeography() {
		return this.geography;
	}

	public void setGeography(String geography) {
		this.geography = geography;
	}

	@Column(name = "modifer", length = 20)
	public String getModifer() {
		return this.modifer;
	}

	public void setModifer(String modifer) {
		this.modifer = modifer;
	}

	@Column(name = "modifydate", length = 10)
	public String getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(String modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * cascade={CascadeType.ALL} mark add
	 * @return
	 */
	@OneToMany(fetch = FetchType.LAZY, cascade=CascadeType.ALL, orphanRemoval=true)
	@JoinColumn(name = "sm_farmer")  
	public Set<TInsectsCollectionOnFarmer> getInsectsCollectionOnFarmers() {
		return this.insectsCollectionOnFarmers;
	}

	public void setInsectsCollectionOnFarmers(Set<TInsectsCollectionOnFarmer> insectsCollectionOnFarmers) {
		this.insectsCollectionOnFarmers = insectsCollectionOnFarmers;
	}

}
