package com.grain.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TGrain generated by hbm2java
 * 粮食表
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_grain")
@JsonIgnoreProperties(value={"hibernateLazyInitializer","handler",
		"grainbin"
		})

public class Grain implements java.io.Serializable {

	private Long id;
	private Grainbin grainbin;
	private String indate;
	private String clxs;
	private String grainname;
	private String harvestdate;
	private String source;
	private Float water;
	private Float impurity;
	private Float grainheight;
	private String dryingmethod;
	private Integer reserveperiod;
	private Integer innum;
	private String container;
	private Integer empty_bin500pa;
	private Integer halfemptybin500pa;
	private Integer fullbin300pa;
	private Integer halffullbin;
	private String storetechnology;
	private String storemethod;
	private String controltemperaturemeasures;
	private String controlhumiditymeasures;
	private Set<GrainPic> grainPics = new HashSet<GrainPic>(0);	//储粮图片
	String modifier;
	String modifytime;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO) 
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lcbm", nullable = false)
	public Grainbin getGrainbin() {
		return this.grainbin;
	}

	public void setGrainbin(Grainbin grainbin) {
		this.grainbin = grainbin;
	}

	@Column(name = "indate", nullable = false, length = 10)
	public String getIndate() {
		return this.indate;
	}

	public void setIndate(String indate) {
		this.indate = indate;
	}

	@Column(name = "clxs", nullable = false, length = 20)
	public String getClxs() {
		return this.clxs;
	}

	public void setClxs(String clxs) {
		this.clxs = clxs;
	}

	@Column(name = "grainname", length = 30)
	public String getGrainname() {
		return this.grainname;
	}

	public void setGrainname(String grainname) {
		this.grainname = grainname;
	}

	@Column(name = "harvestdate", length = 10)
	public String getHarvestdate() {
		return this.harvestdate;
	}

	public void setHarvestdate(String harvestdate) {
		this.harvestdate = harvestdate;
	}

	@Column(name = "source", length = 30)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "water", precision = 12, scale = 0)
	public Float getWater() {
		return this.water;
	}

	public void setWater(Float water) {
		this.water = water;
	}

	@Column(name = "impurity", precision = 12, scale = 0)
	public Float getImpurity() {
		return this.impurity;
	}

	public void setImpurity(Float impurity) {
		this.impurity = impurity;
	}

	@Column(name = "grainheight", precision = 12, scale = 0)
	public Float getGrainheight() {
		return this.grainheight;
	}

	public void setGrainheight(Float grainheight) {
		this.grainheight = grainheight;
	}

	@Column(name = "dryingmethod", length = 30)
	public String getDryingmethod() {
		return this.dryingmethod;
	}

	public void setDryingmethod(String dryingmethod) {
		this.dryingmethod = dryingmethod;
	}

	@Column(name = "reserveperiod")
	public Integer getReserveperiod() {
		return this.reserveperiod;
	}

	public void setReserveperiod(Integer reserveperiod) {
		this.reserveperiod = reserveperiod;
	}

	@Column(name = "innum")
	public Integer getInnum() {
		return this.innum;
	}

	public void setInnum(Integer innum) {
		this.innum = innum;
	}

	@Column(name = "container", length = 60)
	public String getContainer() {
		return this.container;
	}

	public void setContainer(String container) {
		this.container = container;
	}

	@Column(name = "emptybin500Pa")
	public Integer getEmpty_bin500pa() {
		return empty_bin500pa;
	}

	public void setEmpty_bin500pa(Integer empty_bin500pa) {
		this.empty_bin500pa = empty_bin500pa;
	}

	@Column(name = "halfemptybin500pa")
	public Integer getHalfemptybin500pa() {
		return this.halfemptybin500pa;
	}

	public void setHalfemptybin500pa(Integer halfemptybin500pa) {
		this.halfemptybin500pa = halfemptybin500pa;
	}

	@Column(name = "fullbin300pa")
	public Integer getFullbin300pa() {
		return this.fullbin300pa;
	}

	public void setFullbin300pa(Integer fullbin300pa) {
		this.fullbin300pa = fullbin300pa;
	}

	@Column(name = "halffullbin")
	public Integer getHalffullbin() {
		return this.halffullbin;
	}

	public void setHalffullbin(Integer halffullbin) {
		this.halffullbin = halffullbin;
	}

	@Column(name = "storetechnology")
	public String getStoretechnology() {
		return this.storetechnology;
	}

	public void setStoretechnology(String storetechnology) {
		this.storetechnology = storetechnology;
	}

	@Column(name = "storemethod", length = 60)
	public String getStoremethod() {
		return this.storemethod;
	}

	public void setStoremethod(String storemethod) {
		this.storemethod = storemethod;
	}

	@Column(name = "controltemperaturemeasures")
	public String getControltemperaturemeasures() {
		return this.controltemperaturemeasures;
	}

	public void setControltemperaturemeasures(String controltemperaturemeasures) {
		this.controltemperaturemeasures = controltemperaturemeasures;
	}

	@Column(name = "controlhumiditymeasures")
	public String getControlhumiditymeasures() {
		return this.controlhumiditymeasures;
	}

	public void setControlhumiditymeasures(String controlhumiditymeasures) {
		this.controlhumiditymeasures = controlhumiditymeasures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGrain", cascade = {CascadeType.ALL })
	public Set<GrainPic> getGrainPics() {
		return this.grainPics;
	}

	public void setGrainPics(Set<GrainPic> grainPics) {
		this.grainPics = grainPics;
	}

	@Column(name = "modifier")
	public String getModifier() {
		return modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}
	
	@Column(name = "modifytime")
	public String getModifytime() {
		return modifytime;
	}

	public void setModifytime(String modifytime) {
		this.modifytime = modifytime;
	}

}
