package com.grain.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TGraindirection generated by hbm2java
 * 储粮区域划分 信息表
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_graindirection")
@JsonIgnoreProperties(value={"hibernateLazyInitializer","handler","areas"})
public class Graindirection implements java.io.Serializable {

	private Long id;
	private String fullname;
	private Set<Area> areas = new HashSet<Area>(0);


	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "fullname", nullable = false, length = 60)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gd")
	public Set<Area> getAreas() {
		return this.areas;
	}

	public void setAreas(Set<Area> areas) {
		this.areas = areas;
	}

}
