package com.grain.entity;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.grain.entity.user.DepotUser;

/**
 * TGrainbin generated by hbm2java
 * 粮仓信息表
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_grainbin")
@JsonIgnoreProperties(value={"hibernateLazyInitializer","handler",
		"binProtecteds","depotusers","binPhosphinefumigations",
		"binInertaerosols","binCas","binAntiphosphines",
		"binFlylines","grains","binInvests",
		"bintypePics","insectsInbinOnDepots","binCleankills",
		"deviceRealdatas","graindepot"
		})
public class Grainbin implements java.io.Serializable {

	private String lcbm;
	private Graindepot graindepot;
	private String binname;  // 粮仓名
	private Float orientation; // 朝向
	private Integer granarynum;  // 廒间数
	private String typebin;
	private Integer capacity;
	private String structureofbody;
	private String structureofroof;
	private Integer designcapacity;
	private Float designgrainheapheight;
	private Float longth;
	private Float width;
	private Float height;
	private String circulatedevice;
	private String circulatefan;
	private String fanway;
	private String elsedevice;
	private String contract;
	private String phone;
	private String note;
	private String modifer;
	private String modifydate;
	private Set<TBinProtected> binProtecteds = new HashSet<TBinProtected>(0);
	private Set<DepotUser> depotusers = new HashSet<DepotUser>(0);
	private Set<TBinPhosphinefumigation> binPhosphinefumigations = new HashSet<TBinPhosphinefumigation>(0);
	private Set<TBinInertaerosol> binInertaerosols = new HashSet<TBinInertaerosol>(0);
	private Set<TBinCa> binCas = new HashSet<TBinCa>(0);
	private Set<TBinAntiphosphine> binAntiphosphines = new HashSet<TBinAntiphosphine>(0);
	private Set<TBinFlyline> binFlylines = new HashSet<TBinFlyline>(0);
	private Set<Grain> grains = new HashSet<Grain>(0);
	private Set<TBinInvest> binInvests = new HashSet<TBinInvest>(0);
	private List<BintypePic> bintypePics = new ArrayList<BintypePic>(0);
	private Set<TInsectsInbinOnDepot> insectsInbinOnDepots = new HashSet<TInsectsInbinOnDepot>(0);
	private Set<TBinCleankill> binCleankills = new HashSet<TBinCleankill>(0);
	private Set<DeviceRealdata> deviceRealdatas = new HashSet<DeviceRealdata>(0);

	@Id
	@Column(name = "lcbm", unique = true, nullable = false, length = 60)
	public String getLcbm() {
		return this.lcbm;
	}

	public void setLcbm(String lcbm) {
		this.lcbm = lcbm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lkbm")
	public Graindepot getGraindepot() {
		return this.graindepot;
	}

	public void setGraindepot(Graindepot graindepot) {
		this.graindepot = graindepot;
	}

	
	
	@Column(name = "binname", length = 30)
	public String getBinname() {
		return binname;
	}

	public void setBinname(String binname) {
		this.binname = binname;
	}

	@Column(name = "orientation", precision = 12, scale = 0)
	public Float getOrientation() {
		return orientation;
	}

	public void setOrientation(Float orientation) {
		this.orientation = orientation;
	}
	
	@Column(name = "granarynum")
	public Integer getGranarynum() {
		return granarynum;
	}

	public void setGranarynum(Integer granarynum) {
		this.granarynum = granarynum;
	}

	@Column(name = "typebin", nullable = false, length = 20)
	public String getTypebin() {
		return this.typebin;
	}

	public void setTypebin(String typebin) {
		this.typebin = typebin;
	}

	@Column(name = "capacity")
	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	@Column(name = "structureofbody", length = 60)
	public String getStructureofbody() {
		return this.structureofbody;
	}

	public void setStructureofbody(String structureofbody) {
		this.structureofbody = structureofbody;
	}

	@Column(name = "structureofroof", length = 60)
	public String getStructureofroof() {
		return this.structureofroof;
	}

	public void setStructureofroof(String structureofroof) {
		this.structureofroof = structureofroof;
	}

	@Column(name = "designcapacity")
	public Integer getDesigncapacity() {
		return this.designcapacity;
	}

	public void setDesigncapacity(Integer designcapacity) {
		this.designcapacity = designcapacity;
	}

	@Column(name = "designgrainheapheight", precision = 12, scale = 0)
	public Float getDesigngrainheapheight() {
		return this.designgrainheapheight;
	}

	public void setDesigngrainheapheight(Float designgrainheapheight) {
		this.designgrainheapheight = designgrainheapheight;
	}

	@Column(name = "longth")
	public Float getLongth() {
		return this.longth;
	}

	public void setLongth(Float longth) {
		this.longth = longth;
	}

	@Column(name = "width")
	public Float getWidth() {
		return this.width;
	}

	public void setWidth(Float width) {
		this.width = width;
	}

	@Column(name = "height")
	public Float getHeight() {
		return this.height;
	}

	public void setHeight(Float height) {
		this.height = height;
	}

	@Column(name = "Circulatedevice", length = 100)
	public String getCirculatedevice() {
		return this.circulatedevice;
	}

	public void setCirculatedevice(String circulatedevice) {
		this.circulatedevice = circulatedevice;
	}

	@Column(name = "Circulatefan", length = 100)
	public String getCirculatefan() {
		return this.circulatefan;
	}

	public void setCirculatefan(String circulatefan) {
		this.circulatefan = circulatefan;
	}

	@Column(name = "fanway", length = 100)
	public String getFanway() {
		return this.fanway;
	}

	public void setFanway(String fanway) {
		this.fanway = fanway;
	}

	@Column(name = "elsedevice")
	@Lob
	public String getElsedevice() {
		return this.elsedevice;
	}

	public void setElsedevice(String elsedevice) {
		this.elsedevice = elsedevice;
	}

	@Column(name = "contract", length = 20)
	public String getContract() {
		return this.contract;
	}

	public void setContract(String contract) {
		this.contract = contract;
	}

	@Column(name = "phone", length = 100)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "note", length = 400)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "modifer", length = 20)
	public String getModifer() {
		return this.modifer;
	}

	public void setModifer(String modifer) {
		this.modifer = modifer;
	}

	@Column(name = "modifydate", length = 10)
	public String getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(String modifydate) {
		this.modifydate = modifydate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGrainbin")
	public Set<TBinProtected> getBinProtecteds() {
		return this.binProtecteds;
	}

	public void setBinProtecteds(Set<TBinProtected> binProtecteds) {
		this.binProtecteds = binProtecteds;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "grainbins", cascade ={ CascadeType.ALL})
	public Set<DepotUser> getDepotusers() {
		return this.depotusers;
	}

	public void setDepotusers(Set<DepotUser> depotusers) {
		this.depotusers = depotusers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGrainbin")
	public Set<TBinPhosphinefumigation> getBinPhosphinefumigations() {
		return this.binPhosphinefumigations;
	}

	public void setBinPhosphinefumigations(Set<TBinPhosphinefumigation> binPhosphinefumigations) {
		this.binPhosphinefumigations = binPhosphinefumigations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGrainbin")
	public Set<TBinInertaerosol> getBinInertaerosols() {
		return this.binInertaerosols;
	}

	public void setBinInertaerosols(Set<TBinInertaerosol> binInertaerosols) {
		this.binInertaerosols = binInertaerosols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGrainbin")
	public Set<TBinCa> getBinCas() {
		return this.binCas;
	}

	public void setBinCas(Set<TBinCa> binCas) {
		this.binCas = binCas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGrainbin")
	public Set<TBinAntiphosphine> getBinAntiphosphines() {
		return this.binAntiphosphines;
	}

	public void setBinAntiphosphines(Set<TBinAntiphosphine> binAntiphosphines) {
		this.binAntiphosphines = binAntiphosphines;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGrainbin")
	public Set<TBinFlyline> getBinFlylines() {
		return this.binFlylines;
	}

	public void setBinFlylines(Set<TBinFlyline> binFlylines) {
		this.binFlylines = binFlylines;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grainbin")
	public Set<Grain> getGrains() {
		return this.grains;
	}

	public void setGrains(Set<Grain> grains) {
		this.grains = grains;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGrainbin")
	public Set<TBinInvest> getBinInvests() {
		return this.binInvests;
	}

	public void setBinInvests(Set<TBinInvest> binInvests) {
		this.binInvests = binInvests;
	}

	//本表操作仓型图片表
	@Valid
	@ElementCollection
	@CollectionTable(name = "t_bintype_pic")
	public List<BintypePic> getBintypePics() {
		return bintypePics;
	}

	public void setBintypePics(List<BintypePic> bintypePics) {
		this.bintypePics = bintypePics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGrainbin")
	public Set<TInsectsInbinOnDepot> getInsectsInbinOnDepots() {
		return this.insectsInbinOnDepots;
	}


	public void setInsectsInbinOnDepots(Set<TInsectsInbinOnDepot> insectsInbinOnDepots) {
		this.insectsInbinOnDepots = insectsInbinOnDepots;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGrainbin")
	public Set<TBinCleankill> getBinCleankills() {
		return this.binCleankills;
	}

	public void setBinCleankills(Set<TBinCleankill> binCleankills) {
		this.binCleankills = binCleankills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TGrainbin")
	public Set<DeviceRealdata> getDeviceRealdatas() {
		return this.deviceRealdatas;
	}

	public void setDeviceRealdatas(Set<DeviceRealdata> deviceRealdatas) {
		this.deviceRealdatas = deviceRealdatas;
	}

}
