package com.grain.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.grain.entity.user.DepotUser;

/**
 * TGraindepot generated by hbm2java
 * 粮库信息表
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_graindepot")
@JsonIgnoreProperties(value={"hibernateLazyInitializer","handler",
		"depotPhosphinefumigations","tdepotInertaerosols","tdepotAntiphosphines",
		"tdepotFlylines","tdepotInvests",
		"tdepotCas","grainbins","tdepotCleankills",
		"depotusers","tdepotProtecteds"
		})
public class Graindepot implements java.io.Serializable {

	private String lkbm;
	private Area area;
	private String lkmc;
	private String lkdz;
	private Double longtitude;
	private Double latitude;
	private Double altitude;
	private Boolean hasreal;
	private Integer totalbin;
	private String postcode;
	private String contact;
	private String phone;
	private String modifier;
	private Date modifydate;
	private String pic;  // mark
	private Set<DepotPhosphinefumigation> depotPhosphinefumigations = new HashSet<DepotPhosphinefumigation>(0);
	private Set<DepotInertaerosol> TDepotInertaerosols = new HashSet<DepotInertaerosol>(0);
	private Set<DepotAntiphosphine> TDepotAntiphosphines = new HashSet<DepotAntiphosphine>(0);
	private Set<DepotFlyline> TDepotFlylines = new HashSet<DepotFlyline>(0);
	private Set<DepotCa> TDepotCas = new HashSet<DepotCa>(0);
	private Set<TDepotInvest> TDepotInvests = new HashSet<TDepotInvest>(0);
	private Set<Grainbin> grainbins = new HashSet<Grainbin>(0);
	private Set<DepotCleankill> TDepotCleankills = new HashSet<DepotCleankill>(0);
	private Set<DepotUser> depotusers = new HashSet<DepotUser>(0);
	private Set<DepotProtected> TDepotProtecteds = new HashSet<DepotProtected>(0);


	@Id
	@Column(name = "lkbm", unique = true, nullable = false, length = 60)
	public String getLkbm() {
		return this.lkbm;
	}

	public void setLkbm(String lkbm) {
		this.lkbm = lkbm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "direct")
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@Column(name = "lkmc", length = 100)
	public String getLkmc() {
		return this.lkmc;
	}

	public void setLkmc(String lkmc) {
		this.lkmc = lkmc;
	}

	@Column(name = "lkdz", length = 200)
	public String getLkdz() {
		return this.lkdz;
	}

	public void setLkdz(String lkdz) {
		this.lkdz = lkdz;
	}

	@Column(name = "longtitude", precision = 22, scale = 0)
	public Double getLongtitude() {
		return this.longtitude;
	}

	public void setLongtitude(Double longtitude) {
		this.longtitude = longtitude;
	}

	@Column(name = "latitude", precision = 22, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "altitude", precision = 22, scale = 0)
	public Double getAltitude() {
		return this.altitude;
	}

	public void setAltitude(Double altitude) {
		this.altitude = altitude;
	}

	@Column(name = "hasreal")
	public Boolean getHasreal() {
		return this.hasreal;
	}

	public void setHasreal(Boolean hasreal) {
		this.hasreal = hasreal;
	}

	@Column(name = "totalbin")
	public Integer getTotalbin() {
		return this.totalbin;
	}

	public void setTotalbin(Integer totalbin) {
		this.totalbin = totalbin;
	}

	@Column(name = "postcode", length = 10)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "contact", length = 20)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "phone", length = 100)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "modifier", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifydate", length = 19)
	public Date getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "graindepot")
	public Set<DepotPhosphinefumigation> getDepotPhosphinefumigations() {
		return this.depotPhosphinefumigations;
	}

	public void setDepotPhosphinefumigations(Set<DepotPhosphinefumigation> depotPhosphinefumigations) {
		this.depotPhosphinefumigations = depotPhosphinefumigations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "graindepot")
	public Set<DepotInertaerosol> getTDepotInertaerosols() {
		return this.TDepotInertaerosols;
	}

	public void setTDepotInertaerosols(Set<DepotInertaerosol> TDepotInertaerosols) {
		this.TDepotInertaerosols = TDepotInertaerosols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "graindepot")
	public Set<DepotAntiphosphine> getTDepotAntiphosphines() {
		return this.TDepotAntiphosphines;
	}

	public void setTDepotAntiphosphines(Set<DepotAntiphosphine> TDepotAntiphosphines) {
		this.TDepotAntiphosphines = TDepotAntiphosphines;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "graindepot")
	public Set<DepotFlyline> getTDepotFlylines() {
		return this.TDepotFlylines;
	}

	public void setTDepotFlylines(Set<DepotFlyline> TDepotFlylines) {
		this.TDepotFlylines = TDepotFlylines;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "graindepot")
	public Set<DepotCa> getTDepotCas() {
		return this.TDepotCas;
	}

	public void setTDepotCas(Set<DepotCa> TDepotCas) {
		this.TDepotCas = TDepotCas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "graindepot")
	public Set<Grainbin> getGrainbins() {
		return this.grainbins;
	}

	public void setGrainbins(Set<Grainbin> grainbins) {
		this.grainbins = grainbins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "graindepot")
	public Set<DepotCleankill> getTDepotCleankills() {
		return this.TDepotCleankills;
	}

	public void setTDepotCleankills(Set<DepotCleankill> TDepotCleankills) {
		this.TDepotCleankills = TDepotCleankills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "graindepot")
	public Set<DepotUser> getDepotusers() {
		return this.depotusers;
	}

	public void setDepotusers(Set<DepotUser> depotusers) {
		this.depotusers = depotusers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "graindepot")
	public Set<DepotProtected> getTDepotProtecteds() {
		return this.TDepotProtecteds;
	}

	public void setTDepotProtecteds(Set<DepotProtected> TDepotProtecteds) {
		this.TDepotProtecteds = TDepotProtecteds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "graindepot")
	public Set<TDepotInvest> getTDepotInvests() {
		return TDepotInvests;
	}

	public void setTDepotInvests(Set<TDepotInvest> tDepotInvests) {
		TDepotInvests = tDepotInvests;
	}
	
	@Column(name = "pic", length = 256)
	public String getPic() {
		return pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}

}
