package com.grain.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TGrainPic generated by hbm2java
 *  储粮图片表，主要存储储粮图片的储藏位置
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_grain_pic")
@JsonIgnoreProperties(value={"hibernateLazyInitializer","handler",
		"tgrain"
		})
public class GrainPic implements java.io.Serializable {

	private int id;
	private Grain TGrain;
	private String pic;


	@Id
	@GeneratedValue(strategy = GenerationType.AUTO) 
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PID")
	public Grain getTGrain() {
		return this.TGrain;
	}

	public void setTGrain(Grain TGrain) {
		this.TGrain = TGrain;
	}

	@Column(name = "pic", nullable = false)
	public String getPic() {
		return this.pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}

}
