package com.grain.entity;
// Generated 2016-3-20 22:47:51 by Hibernate Tools 3.5.0.Final

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.servlet.http.HttpServletRequest;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.context.request.RequestAttributes;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

import com.grain.CommonAttributes;
import com.grain.Principal;

/**
 * 氮气气调分仓调研表 TBinCa generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_bin_ca")
public class TBinCa implements java.io.Serializable {

	private Long id;
	private Grainbin TGrainbin;
	private Integer annual;
	private Float nitrogendevice;
	private Float controlsystem;
	private Float aircompressor;
	private Float nitrogenroom;
	private Float respirator;
	private Float pipleandfee;
	private Float airpump;
	private Float cableandfee;
	private Float hypoxiaalarm;
	private Float auxiliaryandfee;
	private Float oxygendetectdevice;
	private Float electricityfee;
	private Float chargetime;
	private String chargepro;
	private Float maxconcentration;
	private Float keeplong;
	private Float avggraintemperature;
	private Float highgraintemperature;
	private Float lowestgraintemperture;
	private Float kindbefca;
	private Float densitybefca;
	private Float kindafterca;
	private Float densityafterca;
	private String varconcentration;
	private Integer noninsects;
	private Float fattyacidvaluebef;
	private Float fattyacidvalueafter;
	private String elsecharacter;
	@DateTimeFormat(pattern="yyyy-MM-dd")
	private Date startdate;
	@DateTimeFormat(pattern="yyyy-MM-dd")
	private Date enddate;
	private String reporter;
	@DateTimeFormat(pattern="yyyy-MM-dd")
	private Date reportdate;
	private String modifier;
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date modifytime;
	private String phone;// 后添加的
	
	@Column(name = "phone")
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public TBinCa() {
	}

	public TBinCa(Long id, Integer annual) {
		this.id = id;
		this.annual = annual;
	}

	public TBinCa(Long id, Grainbin TGrainbin, Integer annual, Float nitrogendevice, Float controlsystem,
			Float aircompressor, Float nitrogenroom, Float respirator, Float pipleandfee, Float airpump,
			Float cableandfee, Float hypoxiaalarm, Float auxiliaryandfee, Float oxygendetectdevice,
			Float electricityfee, Float chargetime, String chargepro, Float maxconcentration, Float keeplong,
			Float avggraintemperature, Float highgraintemperature, Float lowestgraintemperture, Float kindbefca,
			Float densitybefca, Float kindafterca, Float densityafterca, String varconcentration, Integer noninsects,
			Float fattyacidvaluebef, Float fattyacidvalueafter, String elsecharacter, Date startdate, Date enddate,
			String reporter, Date reportdate, String modifier, Date modifytime) {
		this.id = id;
		this.TGrainbin = TGrainbin;
		this.annual = annual;
		this.nitrogendevice = nitrogendevice;
		this.controlsystem = controlsystem;
		this.aircompressor = aircompressor;
		this.nitrogenroom = nitrogenroom;
		this.respirator = respirator;
		this.pipleandfee = pipleandfee;
		this.airpump = airpump;
		this.cableandfee = cableandfee;
		this.hypoxiaalarm = hypoxiaalarm;
		this.auxiliaryandfee = auxiliaryandfee;
		this.oxygendetectdevice = oxygendetectdevice;
		this.electricityfee = electricityfee;
		this.chargetime = chargetime;
		this.chargepro = chargepro;
		this.maxconcentration = maxconcentration;
		this.keeplong = keeplong;
		this.avggraintemperature = avggraintemperature;
		this.highgraintemperature = highgraintemperature;
		this.lowestgraintemperture = lowestgraintemperture;
		this.kindbefca = kindbefca;
		this.densitybefca = densitybefca;
		this.kindafterca = kindafterca;
		this.densityafterca = densityafterca;
		this.varconcentration = varconcentration;
		this.noninsects = noninsects;
		this.fattyacidvaluebef = fattyacidvaluebef;
		this.fattyacidvalueafter = fattyacidvalueafter;
		this.elsecharacter = elsecharacter;
		this.startdate = startdate;
		this.enddate = enddate;
		this.reporter = reporter;
		this.reportdate = reportdate;
		this.modifier = modifier;
		this.modifytime = modifytime;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lcbm")
	public Grainbin getTGrainbin() {
		return this.TGrainbin;
	}

	public void setTGrainbin(Grainbin TGrainbin) {
		this.TGrainbin = TGrainbin;
	}

	@Column(name = "Annual", nullable = false)
	public Integer getAnnual() {
		return this.annual;
	}

	public void setAnnual(Integer annual) {
		this.annual = annual;
	}

	@Column(name = "Nitrogendevice", precision = 12, scale = 0)
	public Float getNitrogendevice() {
		return this.nitrogendevice;
	}

	public void setNitrogendevice(Float nitrogendevice) {
		this.nitrogendevice = nitrogendevice;
	}

	@Column(name = "controlsystem", precision = 12, scale = 0)
	public Float getControlsystem() {
		return this.controlsystem;
	}

	public void setControlsystem(Float controlsystem) {
		this.controlsystem = controlsystem;
	}

	@Column(name = "Aircompressor", precision = 12, scale = 0)
	public Float getAircompressor() {
		return this.aircompressor;
	}

	public void setAircompressor(Float aircompressor) {
		this.aircompressor = aircompressor;
	}

	@Column(name = "Nitrogenroom", precision = 12, scale = 0)
	public Float getNitrogenroom() {
		return this.nitrogenroom;
	}

	public void setNitrogenroom(Float nitrogenroom) {
		this.nitrogenroom = nitrogenroom;
	}

	@Column(name = "Respirator", precision = 12, scale = 0)
	public Float getRespirator() {
		return this.respirator;
	}

	public void setRespirator(Float respirator) {
		this.respirator = respirator;
	}

	@Column(name = "pipleandfee", precision = 12, scale = 0)
	public Float getPipleandfee() {
		return this.pipleandfee;
	}

	public void setPipleandfee(Float pipleandfee) {
		this.pipleandfee = pipleandfee;
	}

	@Column(name = "airpump", precision = 12, scale = 0)
	public Float getAirpump() {
		return this.airpump;
	}

	public void setAirpump(Float airpump) {
		this.airpump = airpump;
	}

	@Column(name = "cableandfee", precision = 12, scale = 0)
	public Float getCableandfee() {
		return this.cableandfee;
	}

	public void setCableandfee(Float cableandfee) {
		this.cableandfee = cableandfee;
	}

	@Column(name = "Hypoxiaalarm", precision = 12, scale = 0)
	public Float getHypoxiaalarm() {
		return this.hypoxiaalarm;
	}

	public void setHypoxiaalarm(Float hypoxiaalarm) {
		this.hypoxiaalarm = hypoxiaalarm;
	}

	@Column(name = "auxiliaryandfee", precision = 12, scale = 0)
	public Float getAuxiliaryandfee() {
		return this.auxiliaryandfee;
	}

	public void setAuxiliaryandfee(Float auxiliaryandfee) {
		this.auxiliaryandfee = auxiliaryandfee;
	}

	@Column(name = "oxygendetectdevice", precision = 12, scale = 0)
	public Float getOxygendetectdevice() {
		return this.oxygendetectdevice;
	}

	public void setOxygendetectdevice(Float oxygendetectdevice) {
		this.oxygendetectdevice = oxygendetectdevice;
	}

	@Column(name = "electricityfee", precision = 12, scale = 0)
	public Float getElectricityfee() {
		return this.electricityfee;
	}

	public void setElectricityfee(Float electricityfee) {
		this.electricityfee = electricityfee;
	}

	@Column(name = "chargetime", precision = 12, scale = 0)
	public Float getChargetime() {
		return this.chargetime;
	}

	public void setChargetime(Float chargetime) {
		this.chargetime = chargetime;
	}

	@Column(name = "chargepro", length = 200)
	public String getChargepro() {
		return this.chargepro;
	}

	public void setChargepro(String chargepro) {
		this.chargepro = chargepro;
	}

	@Column(name = "maxconcentration", precision = 12, scale = 0)
	public Float getMaxconcentration() {
		return this.maxconcentration;
	}

	public void setMaxconcentration(Float maxconcentration) {
		this.maxconcentration = maxconcentration;
	}

	@Column(name = "keeplong", precision = 12, scale = 0)
	public Float getKeeplong() {
		return this.keeplong;
	}

	public void setKeeplong(Float keeplong) {
		this.keeplong = keeplong;
	}

	@Column(name = "avggraintemperature", precision = 12, scale = 0)
	public Float getAvggraintemperature() {
		return this.avggraintemperature;
	}

	public void setAvggraintemperature(Float avggraintemperature) {
		this.avggraintemperature = avggraintemperature;
	}

	@Column(name = "highgraintemperature", precision = 12, scale = 0)
	public Float getHighgraintemperature() {
		return this.highgraintemperature;
	}

	public void setHighgraintemperature(Float highgraintemperature) {
		this.highgraintemperature = highgraintemperature;
	}

	@Column(name = "lowestgraintemperture", precision = 12, scale = 0)
	public Float getLowestgraintemperture() {
		return this.lowestgraintemperture;
	}

	public void setLowestgraintemperture(Float lowestgraintemperture) {
		this.lowestgraintemperture = lowestgraintemperture;
	}

	@Column(name = "kindbefca", precision = 12, scale = 0)
	public Float getKindbefca() {
		return this.kindbefca;
	}

	public void setKindbefca(Float kindbefca) {
		this.kindbefca = kindbefca;
	}

	@Column(name = "densitybefca", precision = 12, scale = 0)
	public Float getDensitybefca() {
		return this.densitybefca;
	}

	public void setDensitybefca(Float densitybefca) {
		this.densitybefca = densitybefca;
	}

	@Column(name = "kindafterca", precision = 12, scale = 0)
	public Float getKindafterca() {
		return this.kindafterca;
	}

	public void setKindafterca(Float kindafterca) {
		this.kindafterca = kindafterca;
	}

	@Column(name = "densityafterca", precision = 12, scale = 0)
	public Float getDensityafterca() {
		return this.densityafterca;
	}

	public void setDensityafterca(Float densityafterca) {
		this.densityafterca = densityafterca;
	}

	@Column(name = "varconcentration", length = 60)
	public String getVarconcentration() {
		return this.varconcentration;
	}

	public void setVarconcentration(String varconcentration) {
		this.varconcentration = varconcentration;
	}

	@Column(name = "noninsects")
	public Integer getNoninsects() {
		return this.noninsects;
	}

	public void setNoninsects(Integer noninsects) {
		this.noninsects = noninsects;
	}

	@Column(name = "fattyacidvaluebef", precision = 12, scale = 0)
	public Float getFattyacidvaluebef() {
		return this.fattyacidvaluebef;
	}

	public void setFattyacidvaluebef(Float fattyacidvaluebef) {
		this.fattyacidvaluebef = fattyacidvaluebef;
	}

	@Column(name = "fattyacidvalueafter", precision = 12, scale = 0)
	public Float getFattyacidvalueafter() {
		return this.fattyacidvalueafter;
	}

	public void setFattyacidvalueafter(Float fattyacidvalueafter) {
		this.fattyacidvalueafter = fattyacidvalueafter;
	}

	@Column(name = "elsecharacter", length = 100)
	public String getElsecharacter() {
		return this.elsecharacter;
	}

	public void setElsecharacter(String elsecharacter) {
		this.elsecharacter = elsecharacter;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startdate", length = 10)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enddate", length = 10)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Column(name = "reporter", length = 60)
	public String getReporter() {
		return this.reporter;
	}

	public void setReporter(String reporter) {
		this.reporter = reporter;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "reportdate", length = 10)
	public Date getReportdate() {
		return this.reportdate;
	}

	public void setReportdate(Date reportdate) {
		this.reportdate = reportdate;
	}

	@Column(name = "modifier", length = 60)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifytime", length = 19)
	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	/**
	 * 持久化前处理
	 */
	@PrePersist
	public void prePersist() {
		SetModify();
	}
	
	/**
	 * 更新前处理
	 */
	@PreUpdate
	public void preUpdate() {
		SetModify();
	}
	
	private void SetModify(){
		RequestAttributes requestAttributes = RequestContextHolder.currentRequestAttributes();
		if (requestAttributes != null) {
			HttpServletRequest request = ((ServletRequestAttributes) requestAttributes).getRequest();
			Principal principal = (Principal) request.getSession().getAttribute(CommonAttributes.Principal);
			if (principal!=null){
				this.modifier = principal.getUsername();
				 DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");  
				this.modifytime = new Date();
			}
		}
	}
	
}
