package com.grain.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.servlet.http.HttpServletRequest;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.context.request.RequestAttributes;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

import com.grain.CommonAttributes;
import com.grain.Principal;

/**
 * 分仓空仓杀虫 TBinCleankill generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_bin_cleankill")
public class TBinCleankill implements java.io.Serializable {

	private Long id;
	private Grainbin TGrainbin;
	private Integer annual;
	private String drug;
	private String drugfactory;
	private String deviceandway;
	private Float device;
	private String brand;
	private Float dosage;
	private Float drugfee;
	private Float protective;
	private Float subsidy;
	private Integer keeplong;
	private Float laborfee;
	private Float otherfee;
	private String applymethod;
	private Float applyonsurface;
	private String otherdeal;
	private Float avggraintemperature;
	private Float densitybef;
	private String kindbef;
	private Float densityafter;
	private String kindaf;
	private Integer noninsects;
	private Date startdate;
	private Date enddate;
	private String reporter;
	private String phone;
	private Date reportdate;
	private String modifier;
	private Date modifydate;

	public TBinCleankill() {
	}

	public TBinCleankill(Long id, int annual) {
		this.id = id;
		this.annual = annual;
	}

	public TBinCleankill(Long id, Grainbin TGrainbin, int annual, String deviceandway, Float device, String brand,
			Float dosage, Float drugfee, Float protective, Float subsidy, Integer keeplong, Float laborfee,
			Float otherfee, String applymethod, Float applyonsurface, String otherdeal, Float avggraintemperature,
			Float densitybef, String kindbef, Float densityafter, Integer noninsects, Date startdate, Date enddate,
			String reporter, Date reportdate, String modifier, Date modifydate) {
		this.id = id;
		this.TGrainbin = TGrainbin;
		this.annual = annual;
		this.deviceandway = deviceandway;
		this.device = device;
		this.brand = brand;
		this.dosage = dosage;
		this.drugfee = drugfee;
		this.protective = protective;
		this.subsidy = subsidy;
		this.keeplong = keeplong;
		this.laborfee = laborfee;
		this.otherfee = otherfee;
		this.applymethod = applymethod;
		this.applyonsurface = applyonsurface;
		this.otherdeal = otherdeal;
		this.avggraintemperature = avggraintemperature;
		this.densitybef = densitybef;
		this.kindbef = kindbef;
		this.densityafter = densityafter;
		this.noninsects = noninsects;
		this.startdate = startdate;
		this.enddate = enddate;
		this.reporter = reporter;
		this.reportdate = reportdate;
		this.modifier = modifier;
		this.modifydate = modifydate;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lcbm", nullable = false)
	public Grainbin getTGrainbin() {
		return this.TGrainbin;
	}

	public void setTGrainbin(Grainbin TGrainbin) {
		this.TGrainbin = TGrainbin;
	}

	@Column(name = "Annual", nullable = false)
	public Integer getAnnual() {
		return this.annual;
	}

	public void setAnnual(Integer annual) {
		this.annual = annual;
	}
	
	@Column(name = "drug", length = 100)
	public String getDrug() {
		return drug;
	}

	public void setDrug(String drug) {
		this.drug = drug;
	}
	
	@Column(name = "drugfactory", length = 100)
	public String getDrugfactory() {
		return drugfactory;
	}

	public void setDrugfactory(String drugfactory) {
		this.drugfactory = drugfactory;
	}

	@Column(name = "deviceandway", length = 100)
	public String getDeviceandway() {
		return this.deviceandway;
	}

	public void setDeviceandway(String deviceandway) {
		this.deviceandway = deviceandway;
	}

	@Column(name = "device", precision = 12, scale = 0)
	public Float getDevice() {
		return this.device;
	}

	public void setDevice(Float device) {
		this.device = device;
	}

	@Column(name = "brand", length = 60)
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@Column(name = "Dosage", precision = 12, scale = 0)
	public Float getDosage() {
		return this.dosage;
	}

	public void setDosage(Float dosage) {
		this.dosage = dosage;
	}

	@Column(name = "drugfee", precision = 12, scale = 0)
	public Float getDrugfee() {
		return this.drugfee;
	}

	public void setDrugfee(Float drugfee) {
		this.drugfee = drugfee;
	}

	@Column(name = "protective", precision = 12, scale = 0)
	public Float getProtective() {
		return this.protective;
	}

	public void setProtective(Float protective) {
		this.protective = protective;
	}

	@Column(name = "subsidy", precision = 12, scale = 0)
	public Float getSubsidy() {
		return this.subsidy;
	}

	public void setSubsidy(Float subsidy) {
		this.subsidy = subsidy;
	}

	@Column(name = "keeplong")
	public Integer getKeeplong() {
		return this.keeplong;
	}

	public void setKeeplong(Integer keeplong) {
		this.keeplong = keeplong;
	}

	@Column(name = "laborfee", precision = 12, scale = 0)
	public Float getLaborfee() {
		return this.laborfee;
	}

	public void setLaborfee(Float laborfee) {
		this.laborfee = laborfee;
	}

	@Column(name = "otherfee", precision = 12, scale = 0)
	public Float getOtherfee() {
		return this.otherfee;
	}

	public void setOtherfee(Float otherfee) {
		this.otherfee = otherfee;
	}

	@Column(name = "applymethod", length = 200)
	public String getApplymethod() {
		return this.applymethod;
	}

	public void setApplymethod(String applymethod) {
		this.applymethod = applymethod;
	}

	@Column(name = "applyonsurface", precision = 12, scale = 0)
	public Float getApplyonsurface() {
		return this.applyonsurface;
	}

	public void setApplyonsurface(Float applyonsurface) {
		this.applyonsurface = applyonsurface;
	}

	@Column(name = "otherdeal", length = 200)
	public String getOtherdeal() {
		return this.otherdeal;
	}

	public void setOtherdeal(String otherdeal) {
		this.otherdeal = otherdeal;
	}

	@Column(name = "avggraintemperature", precision = 12, scale = 0)
	public Float getAvggraintemperature() {
		return this.avggraintemperature;
	}

	public void setAvggraintemperature(Float avggraintemperature) {
		this.avggraintemperature = avggraintemperature;
	}

	@Column(name = "densitybef", precision = 12, scale = 0)
	public Float getDensitybef() {
		return this.densitybef;
	}

	public void setDensitybef(Float densitybef) {
		this.densitybef = densitybef;
	}

	@Column(name = "kindbef", length = 100)
	public String getKindbef() {
		return this.kindbef;
	}

	public void setKindbef(String kindbef) {
		this.kindbef = kindbef;
	}

	@Column(name = "densityafter", precision = 12, scale = 0)
	public Float getDensityafter() {
		return this.densityafter;
	}

	public void setDensityafter(Float densityafter) {
		this.densityafter = densityafter;
	}
	
	@Column(name = "kindaf", length = 100)
	public String getKindaf() {
		return kindaf;
	}

	public void setKindaf(String kindaf) {
		this.kindaf = kindaf;
	}

	@Column(name = "noninsects")
	public Integer getNoninsects() {
		return this.noninsects;
	}

	public void setNoninsects(Integer noninsects) {
		this.noninsects = noninsects;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startdate", length = 10)
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enddate", length = 10)
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Column(name = "reporter", length = 20)
	public String getReporter() {
		return this.reporter;
	}

	public void setReporter(String reporter) {
		this.reporter = reporter;
	}
	
	@Column(name = "phone", length = 30)
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "reportdate", length = 10)
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	public Date getReportdate() {
		return this.reportdate;
	}

	public void setReportdate(Date reportdate) {
		this.reportdate = reportdate;
	}

	@Column(name = "modifier", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifydate", length = 19)
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	public Date getModifydate() {
		return this.modifydate;
	}
	
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}
	
	 /**
		 * 持久化前处理
		 */
		@PrePersist
		public void prePersist() {
			SetModify();
		}
		
		/**
		 * 更新前处理
		 */
		@PreUpdate
		public void preUpdate() {
			SetModify();
		}
		
		private void SetModify(){
			RequestAttributes requestAttributes = RequestContextHolder.currentRequestAttributes();
			if (requestAttributes != null) {
				HttpServletRequest request = ((ServletRequestAttributes) requestAttributes).getRequest();
				Principal principal = (Principal) request.getSession().getAttribute(CommonAttributes.Principal);
				if (principal!=null){
					this.modifier = principal.getUsername();
					this.modifydate = new Date();
				}
			}
		}

}
