package com.grain.entity;
// Generated 2016-3-20 22:47:51 by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.Valid;

/**
 * 数字识别特征 generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_digital_feature")
public class TDigitalFeature implements java.io.Serializable {

	private Long id;
	private TCatalogIndex TCatalogIndex;
	private String name;
	private String value;
	private Integer indentifyindex;
	private String note;
	private String source;
	private String modifer;
	private Date modifydate;
	private List<TDigitalPic> TDigitalPics = new ArrayList<TDigitalPic>(0);


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PID")
	public TCatalogIndex getTCatalogIndex() {
		return this.TCatalogIndex;
	}

	public void setTCatalogIndex(TCatalogIndex TCatalogIndex) {
		this.TCatalogIndex = TCatalogIndex;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "indentifyindex", nullable = false)
	public Integer getIndentifyindex() {
		return this.indentifyindex;
	}

	public void setIndentifyindex(Integer indentifyindex) {
		this.indentifyindex = indentifyindex;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "source", length = 100)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "modifer", length = 30)
	public String getModifer() {
		return this.modifer;
	}

	public void setModifer(String modifer) {
		this.modifer = modifer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifydate", length = 19)
	public Date getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}
	@Valid
	@ElementCollection
	@CollectionTable(name = "t_digital_pic")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDigitalFeature")
	public List<TDigitalPic> getTDigitalPics() {
		return this.TDigitalPics;
	}

	public void setTDigitalPics(List<TDigitalPic> TDigitalPics) {
		this.TDigitalPics = TDigitalPics;
	}
	

}
