package com.location.entity;
// Generated 2016-11-26 12:39:38 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LsUserArea generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ls_user_area", catalog = "graininsects")
public class UserArea implements java.io.Serializable {

	private int userId;
	private int areaId;
	private Date starttime;
	private Date endtime;
	private String remark;

	public UserArea() {
	}

	public UserArea(int userId, int areaId) {
		this.userId = userId;
		this.areaId = areaId;
	}
	public UserArea(int userId, int areaId, Date starttime, Date endtime,
			String remark) {
		this.userId = userId;
		this.areaId = areaId;
		this.starttime = starttime;
		this.endtime = endtime;
		this.remark = remark;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "area_id", nullable = false)
	public int getAreaId() {
		return this.areaId;
	}

	public void setAreaId(int areaId) {
		this.areaId = areaId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "starttime", length = 19)
	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endtime", length = 19)
	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	@Column(name = "remark", length = 300)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
